// ─── Images pool ──────────────────────────────────────────────────────────────

export const IMAGES = [
  "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1531482615713-2afd69097998?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?q=80&w=1200&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1555529902-5261145633bf?q=80&w=1200&auto=format&fit=crop",
];

export const FALLBACK = "https://images.unsplash.com/photo-1618477388954-7852f32655ec?q=80&w=800&auto=format&fit=crop";

export const CATEGORY_COLORS = {
  'חדשנות פדגוגית': { bg: 'bg-blue-50', text: 'text-[#007AFF]', dot: 'bg-[#007AFF]' },
  'מעבדות STEM': { bg: 'bg-emerald-50', text: 'text-emerald-600', dot: 'bg-emerald-500' },
  'טרנדים': { bg: 'bg-purple-50', text: 'text-purple-600', dot: 'bg-purple-500' },
  'מקרי בוחן': { bg: 'bg-orange-50', text: 'text-orange-600', dot: 'bg-orange-500' },
  'תשתיות': { bg: 'bg-slate-100', text: 'text-slate-600', dot: 'bg-slate-500' },
  'בינה מלאכותית': { bg: 'bg-violet-50', text: 'text-violet-600', dot: 'bg-violet-500' },
};

// ─── Static Articles ──────────────────────────────────────────────────────────

export const STATIC_ARTICLES = [
  // חדשנות פדגוגית
  { id: 1, category: "חדשנות פדגוגית", title: "איך להפיק את המרב מטכנולוגיית הכיתה: מדריך ה-ROI", excerpt: "מחקר מראה כי שילוב נכון של מסכים אינטראקטיביים מייצר תשואה אמיתית — במעורבות, בחיסכון זמן ובשיפור בהישגים. סקירה מקצועית עם נתוני שטח.", date: "17 מאי 2024", readTime: "6 דק׳", image: IMAGES[0], url: "https://www.eschoolnews.com/digital-learning/2024/05/17/interactive-whiteboard-roi-classroom-edtech/", source: "eSchool News" },
  { id: 2, category: "חדשנות פדגוגית", title: "למידה מבוססת פרויקטים שמערבת את כל התלמידים", excerpt: "למידה מבוססת פרויקטים מקדמת את ארבעת כישורי המאה ה-21: חשיבה ביקורתית, שיתוף פעולה, תקשורת ויצירתיות. הדגשת קול התלמיד ומרחב בחירה הופכים את החוויה למשמעותית ומניעה.", date: "26 ספטמבר 2024", readTime: "6 דק׳", image: IMAGES[4], url: "https://www.edutopia.org/article/project-based-learning-engages-all-students", source: "Edutopia" },
  { id: 3, category: "חדשנות פדגוגית", title: "שימוש בכלי AI לתמיכה בלמידה מבוססת פרויקטים", excerpt: "שילוב AI בלמידה מבוססת פרויקטים מאפשר לתלמידים גישה לכלים שמסייעים לחקור, ליצור ולשפר עבודות. המאמר מסביר כיצד להטמיע AI בצורה פדגוגית נכונה שמחזקת ולא מחליפה את חשיבת התלמיד.", date: "20 יוני 2025", readTime: "5 דק׳", image: IMAGES[1], url: "https://www.edutopia.org/article/using-ai-tools-support-pbl/", source: "Edutopia" },
  { id: 4, category: "חדשנות פדגוגית", title: "שיטות SEL לניהול כיתה אפקטיבי", excerpt: "למידה חברתית-רגשית כוללת בניית מיומנויות מעשיות כמו ניהול פרויקטים קבוצתיים, התמודדות עם לחץ ופתרון קונפליקטים. שילוב SEL בהוראה האקדמית מגביר מוטיבציה והישגים.", date: "15 אוקטובר 2024", readTime: "4 דק׳", image: IMAGES[2], url: "https://www.edutopia.org/article/sel-strategies-classroom-management/", source: "Edutopia" },
  { id: 5, category: "חדשנות פדגוגית", title: "למידה מבוססת פרויקטים: להעמיק ולא למהר", excerpt: "חדשנות אמיתית בכיתה מתרחשת כאשר תלמידים חוזרים שוב ושוב לשגרות מרכזיות, במקום לרוץ לפרויקט הבא. העיקרון: פחות הוא יותר כשמדובר בפרויקטים משמעותיים.", date: "19 נובמבר 2025", readTime: "5 דק׳", image: IMAGES[3], url: "https://www.edutopia.org/article/refining-project-based-learning-emphasizing-depth/", source: "Edutopia" },

  // מעבדות STEM
  { id: 6, category: "מעבדות STEM", title: "כיצד לתכנן מעבדת מדעים מוכנה לעתיד", excerpt: "מדריך מעשי לתכנון ועיצוב מעבדות STEM מודרניות — מהפריסה הפיזית ועד לשילוב ציוד דיגיטלי, כולל שיקולי בטיחות ותחזוקה.", date: "אוגוסט 2023", readTime: "8 דק׳", image: IMAGES[1], url: "https://www.techlearning.com/news/how-to-design-future-ready-science-labs", source: "Tech & Learning" },
  { id: 7, category: "מעבדות STEM", title: "שלוש דרכים לשלב עקרונות מייקרספייס בשיעורי STEM", excerpt: "מורי מדעים ומתמטיקה יכולים לשלב פעילויות יצירה מעשיות — חיתוך לייזר ותכנות — בשיעורים רגילים, מבלי לדרוש חדר מייקרספייס ייעודי. המורים מדווחים על עלייה ניכרת במוטיבציה.", date: "14 נובמבר 2024", readTime: "5 דק׳", image: IMAGES[5], url: "https://www.edutopia.org/article/makerspace-integration-stem-classes/", source: "Edutopia" },
  { id: 8, category: "מעבדות STEM", title: "כיצד בתי ספר יוצרים ומשתמשים במייקרספייסים", excerpt: "מחוזות ברחבי ארה\"ב בנו מרחבי יצירה מצוידים שמאפשרים לתלמידים לעצב, להמציא ולהתנסות ברובוטיקה ותכנות. השקעה בתשתיות אלו מייצרת ערך פדגוגי לטווח ארוך.", date: "מרץ 2024", readTime: "6 דק׳", image: IMAGES[6], url: "https://www.techlearning.com/resources/making-the-grade-how-schools-are-creating-and-using-makerspaces", source: "Tech & Learning" },
  { id: 9, category: "מעבדות STEM", title: "שילוב STEM מוקדם: קידוד, רובוטיקה ומדעים מגיל צעיר", excerpt: "מחקרים מראים כי חשיפה מוקדמת לקידוד ורובוטיקה מפתחת חשיבה אלגוריתמית שנשמרת לאורך שנות הלמידה. ההשקעה בגיל הרך נושאת פירות בהישגים מדעיים בחטיבה ובתיכון.", date: "אוגוסט 2024", readTime: "5 דק׳", image: IMAGES[0], url: "https://www.techlearning.com/news/how-implementing-coding-stem-and-robotics-early-can-benefit-students", source: "Tech & Learning" },
  { id: 10, category: "מעבדות STEM", title: "שילוב כישורי STEM לאורך תכנית הלימודים", excerpt: "בתי ספר משלבים STEM לא רק בשיעורי מדעים אלא גם בהיסטוריה, אמנות ושפה. שילוב רוחבי זה מכין תלמידים לעולם עבודה רב-תחומי הנדרש בשוק ה-AI.", date: "אוגוסט 2025", readTime: "4 דק׳", image: IMAGES[3], url: "https://www.edutopia.org/article/integrating-stem-skills-across-curriculum/", source: "Edutopia" },

  // טרנדים
  { id: 11, category: "טרנדים", title: "5 טרנדים שיעצבו את ה-EdTech ב-2026", excerpt: "EdSurge מנתחת את המגמות המרכזיות בחינוך K-12: מ-AI אישי ועד לכלים שמודדים מעורבות תלמידים — מה שמנהלי מוסדות צריכים לדעת.", date: "27 ינואר 2026", readTime: "5 דק׳", image: IMAGES[2], url: "https://www.edsurge.com/news/2026-01-27-k-12-edtech-in-2026-five-trends-shaping-the-year-ahead", source: "EdSurge" },
  { id: 12, category: "טרנדים", title: "המבט קדימה: טרנדים בחינוך K-12 לשנת 2026", excerpt: "ניתוח מקיף בוחן כיצד מגמות AI, ממשל נתונים ואחריות מדידה ישנו את פני ה-EdTech. המחוזות עוברים ממנטליות של רכישה לממשל מאסטרטגי של כלים קיימים.", date: "15 ינואר 2026", readTime: "6 דק׳", image: IMAGES[7], url: "https://www.edsurge.com/news/2026-01-15-peering-into-the-future-look-for-these-k-12-education-trends-in-2026", source: "EdSurge" },
  { id: 13, category: "טרנדים", title: "10 הסיפורים שקוראי K-12 לא יכלו להפסיק לקרוא ב-2024", excerpt: "מורים חיפשו בעיקר מידע על AI בכיתה, נגישות טכנולוגית לתלמידים עם מוגבלויות ותוצאות למידה מדידות. הציבור הפדגוגי מעוניין בראיות, לא בהבטחות שיווקיות.", date: "9 ינואר 2025", readTime: "5 דק׳", image: IMAGES[4], url: "https://www.edsurge.com/news/2025-01-09-here-are-the-10-stories-k-12-readers-couldn-t-put-down-in-2024", source: "EdSurge" },
  { id: 14, category: "טרנדים", title: "האם הגיע הזמן לזנוח את רעיון ה'הפרעה' ב-EdTech?", excerpt: "מסגרת ה'הפרעה טכנולוגית' בחינוך הוכיחה עצמה כבלתי מועילה. במקומה מציגים חוקרים גישה של 'שיפור מתמיד ומדיד'. המעבר מחשיבת סטארטאפ לחשיבת מוסד חינוכי הוא המפתח.", date: "12 אפריל 2024", readTime: "6 דק׳", image: IMAGES[1], url: "https://www.edsurge.com/news/2024-04-12-it-s-time-to-ditch-the-idea-of-edtech-disruption-but-what-comes-next", source: "EdSurge" },
  { id: 15, category: "טרנדים", title: "טכנולוגיית כיתה: הישנה, החדשה — ומה באמת עובד", excerpt: "מה ממשיך לעבוד ומה חדש בטכנולוגיות כיתה ב-2024? סקירה על כלים שמורים באמת משתמשים בהם — ולמה.", date: "20 פברואר 2024", readTime: "7 דק׳", image: IMAGES[3], url: "https://www.eschoolnews.com/innovative-teaching/2024/02/20/classroom-technology-new-tried-and-true/", source: "eSchool News" },

  // מקרי בוחן
  { id: 16, category: "מקרי בוחן", title: "LAUSD משיקה כלי AI מהפכני לתלמידים, הורים ומורים", excerpt: "מחוז לוס אנג'לס, השני בגודלו בארה\"ב, הפך לראשון שמיישם AI בקנה מידה מערכתי. כלי AI ייעודי עוזר לתלמידים בשיעורי בית ולמורים בתכנון שיעורים — מקרה בוחן שמחוזות רבים עוקבים אחריו.", date: "26 מרץ 2024", readTime: "5 דק׳", image: IMAGES[2], url: "https://www.eschoolnews.com/digital-learning/2024/03/26/lausd-launches-revolutionary-ai-tool/", source: "eSchool News" },
  { id: 17, category: "מקרי בוחן", title: "למידה מותאמת אישית בקנה מידה: האם ניתן לסגור פערי הישגים?", excerpt: "מחקר מקיף בוחן תוכניות למידה מותאמת אישית ב-10 מחוזות ומנסה לענות: האם הטכנולוגיה באמת סוגרת פערים? מחוזות שהשקיעו בליווי פדגוגי ראו תוצאות טובות פי שניים.", date: "28 מרץ 2022", readTime: "8 דק׳", image: IMAGES[5], url: "https://www.edsurge.com/news/2022-03-28-can-personalized-learning-be-scaled-to-ease-teacher-burdens-and-close-achievement-gaps", source: "EdSurge" },
  { id: 18, category: "מקרי בוחן", title: "בתי ספר מחזיקים מוצרי EdTech בסטנדרט גבוה יותר", excerpt: "מחוזות מוסיפים תהליכי ביקורת מחמירים לפני רכישת כלים טכנולוגיים ודורשים ראיות מחקריות. השינוי בתרבות הרכישה הוביל לחיסכון משמעותי ולתוצאות טובות יותר.", date: "5 אוגוסט 2024", readTime: "5 דק׳", image: IMAGES[0], url: "https://www.edsurge.com/news/2024-08-05-how-schools-are-holding-edtech-products-to-a-higher-standard", source: "EdSurge" },
  { id: 19, category: "מקרי בוחן", title: "חמישה דברים שצריך לדעת על תגבור לימודי אינטנסיבי", excerpt: "תגבור לימודי אינטנסיבי — שלוש פעמים בשבוע ומעלה — הוא אחד הכלים האפקטיביים ביותר לסגירת פערים לאחר הקורונה. עלות-תועלת הגישה מוצגת עם נתונים מדידים.", date: "26 פברואר 2024", readTime: "4 דק׳", image: IMAGES[6], url: "https://www.eschoolnews.com/educational-leadership/2024/02/26/5-things-to-know-about-high-dosage-tutoring/", source: "eSchool News" },
  { id: 20, category: "מקרי בוחן", title: "שילוט דיגיטלי בחינוך: הכלים שמורים צריכים", excerpt: "כיצד שילוט דיגיטלי משדרג תקשורת מוסדית, מפחית עומס מנהלי ומאפשר למורים לחזור להוראה — עם דוגמאות מהשטח.", date: "אוקטובר 2023", readTime: "4 דק׳", image: IMAGES[7], url: "https://www.eschoolnews.com/featured/2020/10/23/digital-signage-offers-teachers-the-tools-they-need-to-succeed/", source: "eSchool News" },

  // תשתיות
  { id: 21, category: "תשתיות", title: "תוכנית הטכנולוגיה הלאומית לחינוך 2024: מה שחייבים לדעת", excerpt: "משרד החינוך האמריקאי פרסם תוכנית הטכנולוגיה הלאומית הראשונה מאז 2016 הפונה לשלושה פערים: גישה, עיצוב ושימוש דיגיטלי. זהו מסמך ייחוס מרכזי לכל מנהל טכנולוגיה מחוזי.", date: "ינואר 2024", readTime: "7 דק׳", image: IMAGES[0], url: "https://www.techlearning.com/news/the-2024-national-educational-technology-plan-is-out-heres-what-you-need-to-know", source: "Tech & Learning" },
  { id: 22, category: "תשתיות", title: "גישור על הפער הדיגיטלי: מחוזות שבנו רשתות אלחוטיות עצמאיות", excerpt: "מחוזות שנאבקו עם חיבור אינטרנט לא אמין הקימו רשתות אלחוטיות משלהם. שיתוף פעולה מקומי פתר בעיות חיבור שחברות הסלולר לא יכלו לפתור — והחזיר מאות תלמידים לזרם הדיגיטלי.", date: "2024", readTime: "5 דק׳", image: IMAGES[4], url: "https://www.techlearning.com/news/overcoming-the-digital-divide-school-districts-create-their-own-wireless-networks", source: "Tech & Learning" },
  { id: 23, category: "תשתיות", title: "בניית רשתות סלולריות גמישות ומאובטחות בבתי ספר", excerpt: "עם התרחבות מכשירי 1:1, תשתית הרשת הפכה לעמוד השדרה הקריטי. המאמר מציג עקרונות ל-WLAN בית ספרי שמסוגל להתמודד עם אלפי מכשירים בו-זמנית.", date: "2024", readTime: "5 דק׳", image: IMAGES[5], url: "https://www.techlearning.com/news/building-flexible-and-secure-mobile-networks-in-schools", source: "Tech & Learning" },
  { id: 24, category: "תשתיות", title: "כיצד בתי ספר צריכים לבחון מחדש אבטחת סייבר בעידן ה-AI", excerpt: "ככל שכלי AI חודרים לסביבת הלמידה, משטח ההתקפה של בתי הספר מתרחב. 66% מהמחוזות אינם מחזיקים אפילו עובד סייבר במשרה מלאה. המאמר מציג מסגרת פרקטית להגנה.", date: "מאי 2024", readTime: "6 דק׳", image: IMAGES[2], url: "https://www.techlearning.com/news/how-schools-should-reassess-cybersecurity-due-to-ai", source: "Tech & Learning" },
  { id: 25, category: "תשתיות", title: "השקעה בתשתית הנכונה: מה מחוזות צריכים לדעת ב-2025", excerpt: "עם כניסת AI לכל כיתה, תשתית ה-IT הופכת למשאב אסטרטגי. המאמר מנחה מנהלי טכנולוגיה מחוזיים בתעדוף השקעות: רוחב פס, ענן, אבטחה ותמיכה.", date: "2025", readTime: "6 דק׳", image: IMAGES[1], url: "https://www.techlearning.com/news/the-new-role-of-the-ed-tech-director", source: "Tech & Learning" },

  // בינה מלאכותית
  { id: 26, category: "בינה מלאכותית", title: "AI בכיתה: למה יותר מורים בוחרים בו — וממה צריך להיזהר", excerpt: "EdWeek חוקרת את הגידול המהיר באימוץ AI בבתי ספר, מה מניע מורים לשלב אותו, ומהן המגבלות שחשוב להכיר לפני.", date: "ינואר 2026", readTime: "6 דק׳", image: IMAGES[1], url: "https://www.edweek.org/technology/more-teachers-are-using-ai-in-their-classrooms-heres-why/2026/01", source: "Education Week" },
  { id: 27, category: "בינה מלאכותית", title: "כיצד AI משנה את החינוך: 5 הסיפורים הגדולים של 2024", excerpt: "Education Week מסכמת את חמשת הסיפורים שסימנו מפנה: פיצוץ בשימוש תלמידי ב-AI, ראשית הסדרת מדיניות מחוזית, וצמיחת כלי זיהוי AI. 85% מהמורים השתמשו ב-AI בשנת הלימודים.", date: "דצמבר 2024", readTime: "6 דק׳", image: IMAGES[7], url: "https://www.edweek.org/technology/how-ai-is-changing-education-the-years-top-5-stories/2024/12", source: "Education Week" },
  { id: 28, category: "בינה מלאכותית", title: "'זה לא קסם': כיצד בתי ספר מלמדים אוריינות AI", excerpt: "מחוזות מפתחים תכניות ייעודיות לאוריינות AI שמסבירות לתלמידים כיצד המערכות עובדות ומה מגבלותיהן. הגישה מכינה דור מוכן לעתיד AI עם חשיבה ביקורתית.", date: "אוקטובר 2025", readTime: "5 דק׳", image: IMAGES[3], url: "https://www.edweek.org/technology/its-not-magic-how-these-schools-are-teaching-ai-literacy/2025/10", source: "Education Week" },
  { id: 29, category: "בינה מלאכותית", title: "יחידת לימוד AI בPBL לתלמידי בית ספר יסודי", excerpt: "תלמידי יסודי משתמשים ב-AI לתכנון ובניית עיר לגו: מגדירים דרישות, מייצרים עיצובים ומשפרים לפי משוב. המורות מדווחות על רמת מעורבות שלא ראו לפני כן.", date: "23 ספטמבר 2024", readTime: "4 דק׳", image: IMAGES[6], url: "https://www.edutopia.org/article/pbl-ai-elementary-students/", source: "Edutopia" },
  { id: 30, category: "בינה מלאכותית", title: "מדיניות AI בבתי ספר: המדריך המעשי למנהלים", excerpt: "עם התפשטות הכלים, מנהלים נדרשים לנסח מדיניות ברורה — מה מותר, מה אסור ואיך לאכוף. המאמר מציג מסגרת מדיניות מעשית שמחוזות מובילים כבר אימצו.", date: "2025", readTime: "5 דק׳", image: IMAGES[4], url: "https://www.edweek.org/technology/ai-policy-schools-administrators-guide/2025", source: "Education Week" },
];
